on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  my_job:
    name: test python and push terraform
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: python -m pip install --upgrade pip boto3 moto
    - name: Run python tests
      run: python .\python\test_UpdateVisitorCount.py
    
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_SECRET_ACCESS_REGION }}
    
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2.0.3    
    - name: run plan
      run: terraform plan
    - name: run apply
      run: terraform apply -auto-approve
      
    
