on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  my_job:
    name: test python and push terraform
    runs-on: windows-latest
    
    steps:
    - name: Setup python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install --upgrade pip boto3 moto
    - name: Run python tests
      run: python .\python\test_UpdateVisitorCount.py
    
